### ISSUE TITLE
Developer Support

### ISSUE THREAD

**Issue by mkld0910** [eldy/SellYourSaas#128]
Bonjour, j'ai cherché à faire appel à un développeur de logiciels pour vous aider à installer votre application. Je ne peux qu'apprécier tout le talent et les compétences qu'il a fallu pour développer ce logiciel. Malheureusement comme tu l'as expliqué

"Sell-Your-Saas fournit une solution complète pour une entreprise 100% automatisée. Elle a besoin de beaucoup de composants Open-Source. Faire une installation automatisée est très difficile et même impossible sur la plupart des fournisseurs car ce n'est pas une application mais un système.
Ce point n'est pas prioritaire pour le moment mais je garde le ticket ouvert pour le futur..."

Êtes-vous ou un membre de votre équipe disponible ou capable d'aider à l'installation puisque votre expertise serait essentielle à une installation réussie.

Je ne connais pas les termes et pratiques de github. J'espère que je n'ai offensé personne ici avec mon enquête. 

Hi have been looking to contract a software programming developer to assist with the install of your application. I can only appreciate all the talent and skill it took to go into the developing of this software. Unfortunately as you articulated 

"Sell-Your-Saas provides a full solution for a 100% automated business. It needs a lot of Open-Source components. Making an automated installation is very difficult and even not possible on most providers because it is not one application but a full system.
This point is not the priority for the moment but i keep the ticket open for future..."

Are you or any of your team available or able to assist with the installation since your expertise would be critical in successful installation.

I am unfamiliar with the terms and practices of github. I hope i have not offended anyone here with my inquiry.

**Comment by eldy** [comment]
Unfortunately, i have no availability to help in making a full install of sellyoursaas (lack of time).
Hiring someone is possible but don't look for a developer. What you need is an experienced "system administrator".
Automating the selling of an application has very complex problems that are solved by sellyoursaas but it means also complex systems to know, and only an experienced sys-admin will be able to understand all the stack.

**Comment by mkld0910** [comment]
Thank you so much for taking the time to this response, Your advice in this matter is greatly appreciated. You made reference that a lot of other open source components are required to make use of the software. Are the necessary components identified in the readme? Unfortunately to a lay person such as myself it was a bit cryptic. Or if its not to great of request can you briefly list the other major open source components that are required so i can better empower the experience system's administrator once i am able to source one.

**Comment by eldy** [comment]
100% of used components are mentionned into the main doc file:
https://github.com/eldy/SellYourSaas/blob/master/doc/Documentation%20SellYourSaas%20-%20Master%20and%20Deployment%20Servers%20-%20EN.asciidoc

**Comment by mkld0910** [comment]
Wonderful thank you so much for everything. I wish you and your collaborators all success.
