### ISSUE TITLE
MariaDB Cluster Master/Slave necessary? + questions

### ISSUE THREAD

**Issue by n00rm** [eldy/SellYourSaas#180]
Hi, 
I'm currently taking a look into this project and I'm reading through the documentation and I wonder if this is really optional because it's not really clear.

Documentation:
https://github.com/eldy/sellyoursaas/blob/master/doc/Documentation%20SellYourSaas%20-%20Master%20and%20Deployment%20Servers%20-%20EN.asciidoc#setup-mariadb-cluster-in-mode-master-slave-optional-abandonned

My question is now. Do you need to setup a Master Slave Maria DB Server or are the Deployment servers are connecting to the master server database?
In the documentation it says optional and abandoned. 

Is it possible to make the install process a bit more detailed. It's really easy to get lost what needs to be done on the master and what needs to be done on the deployment server. Another thing that I miss is a little picture that shows how everything is communicating with each other. Like where runs what and how is it done from a technical point of view. That would help so much.

Thanks in advance!

**Comment by eldy** [comment]
Yes, replication here of master is clearly useless . Even a database failure will just break temporarely new registrations, and invoicing and does not affect customers/users.
