### ISSUE TITLE
error generate pdf

### ISSUE THREAD

**Issue by dnit71** [eldy/sellyoursaas#87]
Hello,
I try to generate the doc in pdf but I get these error when I launch the command : 
asciidoctor-pdf -a pdf-themesdir=. -a pdf-theme=sellyoursaas "Documentation\ SellYourSaas\ -\ Master\ and\ Deployment\ Servers\ -\ FR.asciidoc"

asciidoctor: ERROR: Documentation SellYourSaas - Master and Deployment Servers - FR.asciidoc: line 1419: level 0 sections can only be used when doctype is book
asciidoctor: ERROR: Documentation SellYourSaas - Master and Deployment Servers - FR.asciidoc: line 1706: level 0 sections can only be used when doctype is book
asciidoctor: WARNING: Documentation SellYourSaas - Master and Deployment Servers - FR.asciidoc: line 5751: unterminated listing block
asciidoctor: ERROR: could not locate or load the pdf theme `sellyoursaas' in .; reverting to default theme
asciidoctor: ERROR: failed to parse formatted text: auto eth0:1 iface eth0:1 inet static address e.f.g.h netmask 255.255.255.255 broadcast e.f.g.h&lt;/.......etc
It generated a pdf but unsubale (see attached).
Could you provide the doc in pdf on the site or github ?
OS : debian 10
[Documentation SellYourSaas - Master and Deployment Servers - FR.pdf](https://github.com/eldy/sellyoursaas/files/5720709/Documentation.SellYourSaas.-.Master.and.Deployment.Servers.-.FR.pdf)

thanks

**Comment by eldy** [comment]
Can you try just  
`asciidoctor-pdf 'Name of file.asciidoc'`
