### ISSUE TITLE
Incorrect template link on customer invoice (multiple domains context)

### ISSUE THREAD

**Issue by flegastelois** [eldy/sellyoursaas#92]
**Describe the bug**

Context: multiple cloud domain managed by one dolibarr master:
- "main-domain.fr" was the first domain
- "my-domain.fr" the second one installed after

In the form of a customer invoice, the domain link for "Généré à partir du modèle de facture" is incorrect, should be on "admin.my-domain.fr" and not "main-domain.fr".

**To Reproduce**
1. log-in on admin."my-domain.fr"
2. go to a customer invoice (which is generated from a template)
3. click on the link to view the "Template that generated this invoice"
4. you have switched to admin."main-domain.fr"

**Screenshots**

![image](https://user-images.githubusercontent.com/470612/104708908-924bab00-571e-11eb-8677-9a0f3c5f2477.png)

**Comment by eldy** [comment]
This was a bug into Dolibarr itself. It has been fixed into v13+ so i close the ticket.
