### ISSUE TITLE
Can upload files on the support request form.

### ISSUE THREAD

**Issue by eldy** [eldy/SellYourSaas#93]

**Comment by hregis** [comment]
@eldy and compatible with Ticket module ?

**Comment by eldy** [comment]
@Hystepik 
Sometimes the user select a file but they forgot to click on button "submit file".
Can you add a test so when the submit a form, if they add a file to upload and did non submit if before, there is an error. You can take the example on common form used to send a dolibarr document by email. There is such a test already.
